version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12.18.2
  steps:
      - checkout
      - run:
          name: Install node modules
          command: npm install
      - run:
          name: Run unit tests
          command: npm test
      - run:
          name: Building android
          command: ionic cordova build android
      - store_artifacts:
          path: platforms/android/build/outputs/apk/android-debug.apk