name: Build Android app

on: # rebuild any PRs and main branch changes
  pull_request:
  push: #spin up ci once there is a chsange in master branch
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install @angular/cli
      run: npm i -D -E @angular/cli
    - name: Use coturiv/setup-ionic
      uses: coturiv/setup-ionic@v1
      with:
        cordova-version: 8
 #switch to java8 from 11 supplied by ubuntu 20.04       
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
#build the app
    - name: Build
      run: ionic cordova build android
#upload the app
    - name: Upload app
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: platforms/android/app/build/outputs/apk/debug/app-debug.apk